# Generated by Django 3.1.6 on 2021-02-06 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('str_nombre', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de creacion')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de actualizacion')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('str_sku', models.CharField(max_length=150, unique=True, verbose_name='Sku')),
                ('str_name', models.CharField(max_length=150, unique=True, verbose_name='Name')),
                ('str_price', models.CharField(max_length=150, unique=True, verbose_name='Price')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de creacion')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de actualizacion')),
            ],
        ),
        migrations.CreateModel(
            name='View',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('str_times', models.CharField(max_length=150, unique=True, verbose_name='times')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de creacion')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de actualizacion')),
                ('obj_products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Products')),
            ],
        ),
    ]
