# Generated by Django 3.1.6 on 2021-02-07 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210206_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='str_price',
            field=models.CharField(max_length=150, verbose_name='Price'),
        ),
    ]
