# Generated by Django 3.1.6 on 2021-02-07 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20210207_0016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='view',
            name='obj_user_login',
        ),
        migrations.AlterField(
            model_name='view',
            name='str_times',
            field=models.CharField(max_length=150, verbose_name='times'),
        ),
    ]
